Repository SR-Sunny-Raj/Hacktoberfest2021-DSA, pull requests merged in 2021-10, with the labels that each got.

#10 Min stack
  11. Stack/Min Stack/Question.txt
  11. Stack/Min Stack/README.md
  11. Stack/Min Stack/Solution.cpp
Labels: hacktoberfest-accepted

#11 Remove duplicates from a sorted list problem added
  10. Linked List/remove-duplicates-from-a-sorted-list.cpp
Labels: hacktoberfest-accepted

#8 Create check_for_bst.cpp
  15. Binary Search Tree/check_for_bst.cpp
Labels: hacktoberfest-accepted

#14 Updated sort_an_array_of_0s_1s_and_2s.cpp
  06. Sorting/1)sort_an_array_of_0s_1s_and_2s.cpp
Labels: hacktoberfest-accepted

#15 Kth Smallest in BST
  15. Binary Search Tree/kth_Smallest_BST.cpp
  16. Heap/1_Median_Of_Running_Stream.cpp
Labels: hacktoberfest-accepted

#16 Created catalan_numbers.cpp
  04. Arrays/catalan_numbers.cpp
Labels: hacktoberfest-accepted

#17 Create Counting_Sort_CPP.cpp
  06. Sorting/Counting_Sort_CPP.cpp
Labels: hacktoberfest-accepted

#18 New Code sliding_window_max_of_all_subarrays.cpp
  12. Queue/sliding_window_max_of_all_subarrays.cpp
Labels: hacktoberfest-accepted

#19 Unique number of occurences problem with solution
  08. Hashing/Unique-number-of-occurrences(Hashing).cpp
Labels: hacktoberfest-accepted

#20 DSA-Hacktoberfest2021
  06. Sorting/Insertion_sort.cpp
  06. Sorting/Merge_sort.cpp
  06. Sorting/Quick_sort.cpp
Labels: hacktoberfest-accepted

#21 Detailed Solution for maximum of minima of window size k
  08. Hashing/Maximum_of_Miminum_K_window.cpp
Labels: hacktoberfest-accepted

#23 added nqueen and sudoku backtracking problems
  19. Backtracking/SudokuSolver.cpp
  19. Backtracking/nqueen.cpp
Labels: hacktoberfest-accepted

#24 Create Partition to K Equal Sum Subsets.cpp
  19. Backtracking/Partition to K Equal Sum Subsets.cpp
Labels: hacktoberfest-accepted

#26 Middle of the Linked List added
  10. Linked List/middle-of-the-linked-list.cpp
Labels: hacktoberfest-accepted

#28 Product of Array Except Self and its solution
  04. Arrays/Product of Array Except Self.cpp
Labels: hacktoberfest-accepted

#29 Minimum Number of Swaps to Make the String Balanced Added
  11. Stack/min-number-of-swaps-to-make-the-string-balanced.cpp
Labels: hacktoberfest-accepted

#32 seg tree sum
  22. Segment Tree/seg.cpp
Labels: hacktoberfest-accepted

#34 linked list implementation
  10. Linked List/linkedlist.cpp
Labels: hacktoberfest-accepted

#35 added two new solution in string folder
  08. Hashing/Maximum_of_Miminum_K_window.cpp
  08. Hashing/Subarrays with sum k.cpp
  08. Hashing/Unique-number-of-occurrences(Hashing).cpp
  09. String/1_Find the Difference.cpp
  09. String/2_ Reformat Date.cpp
Labels: hacktoberfest-accepted

#41 code added
  04. Arrays/2_Remove duplicate elements from sorted Array.cpp
Labels: hacktoberfest-accepted

#39 created merge two sorted lists & solved.
  10. Linked List/Merge Two Sorted Lists.cpp
Labels: hacktoberfest-accepted

#43 Created sieve_of_eratosthenes.cpp
  01. Mathematics/sieve_of_eratosthenes.cpp
Labels: hacktoberfest-accepted

#45 Missing number from array of first N numbers Added
  01. Mathematics/12_Missing-number-in-array.cpp
Labels: hacktoberfest-accepted

#44 dp coin_change_problem
  20. Dynamic Programming/coin_change.cpp
Labels: hacktoberfest-accepted

#47 Create and add heap sort
  06. Sorting/heap sort.cpp
Labels: hacktoberfest-accepted

#46 Rotate List to the right by k places
  10. Linked List/Remove_Nth_node_from_end_of_the_List
  10. Linked List/Rotate_List_to_the_right_by_k_places
Labels: hacktoberfest-accepted

#48 C++ program to find the length of longest subsequence present in given two strings.
  20. Dynamic Programming/Longest_Common_Subsequence.cpp
Labels: hacktoberfest-accepted

#49 Create trapping-water.cpp
  04. Arrays/trapping-water.cpp
Labels: hacktoberfest-accepted

#33 Added Maximum Depth of Binary Tree
  11. Stack/nearest-smaller-element.cpp
  15. Binary Search Tree/maximum-depth-of-binary-tree.cpp
Labels: hacktoberfest-accepted

#51 Create Split Linked List In Parts
  04. Arrays/Maximum_Consecutive_ones
  10. Linked List/Split_Linked_List_In_Parts
Labels: hacktoberfest-accepted

#37 Convert Sorted List to Binary Search Tree Added
  15. Binary Search Tree/convert-sorted-list-to-binary-search-tree.cpp
Labels: hacktoberfest-accepted

#53 Create Sort_By_Parity
  04. Arrays/Sort_By_Parity
Labels: hacktoberfest-accepted

#54 Maximum Subarray Sum (via Kadane's algorithm).cpp
  04. Arrays/Maximum Subarray Sum (via Kadane's algorithm).cpp
Labels: hacktoberfest-accepted

#52 Create triplet-sum.cpp
  04. Arrays/triplet-sum.cpp
Labels: hacktoberfest-accepted

#58 Queueusing2Stacks
  12. Queue/Queueusing2Stacks.cpp
Labels: hacktoberfest-accepted

#59 Added a chocolate distribution problem using greedy
  18. Greedy/chocolate_distribution.cpp
Labels: hacktoberfest-accepted

#62 My mathematical approach that solves this question in O(1) time.
  01. Mathematics/18_number_of_spirals.cpp
Labels: hacktoberfest-accepted

#64 Added third largest element
  04. Arrays/11_find transition.cpp
  04. Arrays/4_Third largest element.cpp
Labels: hacktoberfest-accepted

#69 Create FourSum.cpp
  04. Arrays/FourSum.cpp
Labels: hacktoberfest-accepted

#57 Created longest_palindromic_subsequence.cpp
  04. Arrays/rain_water_trapping.cpp
  20. Dynamic Programming/longest_palindromic_subsequence.cpp
Labels: hacktoberfest-accepted

#65 added code
  05. Searching/6-Kadens-largest-subarray.cpp
Labels: hacktoberfest-accepted

#66 Added a program to find zig-zag traversal in tree
  14. Tree/Zig-Zag-traversal.cpp
Labels: hacktoberfest-accepted

#73 insert and delete an element of array.cpp
  04. Arrays/insert and delete an element of array.cpp
Labels: hacktoberfest-accepted

#72 Radix Sort
  06. Sorting/RadixSort.exe
Labels: duplicate, hacktoberfest-accepted

#71 Added Solution to Leetcode Problem Repeated DNA Sequences Problem
  04. Arrays/repeated_DNA_sequences.cpp
Labels: hacktoberfest-accepted

#70 Create Solution Q1.cpp
  02. Bit Magic/Solution Q1.cpp
Labels: hacktoberfest-accepted

#67 Created minimize_max_difference_adjacent_elements.cpp
  12. Queue/minimize_max_difference_adjacent_elements.cpp
Labels: hacktoberfest-accepted

#79 Added cpp solution to word break problem
  20. Dynamic Programming/word_break.cpp
Labels: hacktoberfest-accepted

#80 Added Stock_span.cpp file
  11. Stack/Stocks_span.cpp
Labels: hacktoberfest-accepted

#81 Added code to create adjacency matrix
  17. Graph/adjacency_matrix.cpp.c
Labels: hacktoberfest-accepted

#74 bfs_iterative
  17. Graph/bfs_iterative.java
Labels: hacktoberfest-accepted

#60 Checking if Linked List is sorted.cpp
  10. Linked List/Checking if Linked List is sorted.cpp
Labels: hacktoberfest-accepted

#82 no of connected components in a graph using dfs
  17. Graph/dfs_connected_components.cpp
Labels: hacktoberfest-accepted

#84 added graph programs
  17. Graph/cycledetectionDGdfs.cpp
  17. Graph/cycledetectionUGbfs.cpp
  17. Graph/cycledetectionUGdfs.cpp
  17. Graph/topologicalsortbfs.cpp
  17. Graph/topologicalsortdfs.cpp
  17. Graph/traversalbfs.cpp
  17. Graph/traversaldfs.cpp
Labels: hacktoberfest-accepted

#83 create traversal-linked-list.cpp
  10. Linked List/traversal-linked-list.cpp
Labels: hacktoberfest-accepted

#77 Sorted Linked List to Binary Search Tree
  10. Linked List/Searching in linked list through iteration and recursion
  15. Binary Search Tree/Sorted Array to Binary Search Tree
  15. Binary Search Tree/Sorted linked list to binary search tree
Labels: hacktoberfest-accepted

#85 Create Two Matrices using Multi-dimensional Arrays
  07. Matrix/martix-adding-multidimensional-array.cpp
Labels: hacktoberfest-accepted

#88 Merge Two BSTs
  15. Binary Search Tree/Merge_Two_BST.cpp
Labels: hacktoberfest-accepted

#89 added new solution to DP, Array, Linked List, String and Matrix
  04. Arrays/12_Find First and Last Position of Element in Sorted Array.cpp
  04. Arrays/13_Combination Sum.cpp
  04. Arrays/14_Russian Doll Envelopes.cpp
  07. Matrix/1_Rotate Image.cpp
  09. String/3_Largest Number.cpp
  10. Linked List/1_Add Two Numbers.cpp
  20. Dynamic Programming/1_Best Time To Buy And Sell Stocks.cpp
Labels: hacktoberfest-accepted

#90 Shortest path using bfs
  17. Graph/Labyrinth.cpp
Labels: hacktoberfest-accepted

#86 Solution to a Codeforces problem
  18. Greedy/Codeforces_Problem_1579E2-38.cpp
Labels: hacktoberfest-accepted

#91 Create Ceil_of_an_element_in_sorted_array.cpp
  05. Searching/Ceil_of_an_element_in_sorted_array.cpp
Labels: hacktoberfest-accepted

#94 Create DetectLoop.cpp
  10. Linked List/DetectLoop.cpp
Labels: hacktoberfest-accepted

#103 Create order-agnostic-search.cpp
  05. Searching/order-agnostic-search.cpp
Labels: hacktoberfest-accepted

#96 Changes in Mathematics/6_AbsoluteValue
  01. Mathematics/6_AbsoluteValue.cpp
Labels: hacktoberfest-accepted

#97 codeforces round 745 C solution
  codeforces_745_C_solution
Labels: hacktoberfest-accepted

#98 Duplicate in an array of n+1 integers
  04. Arrays/duplicateInArrayOfn+1integers.java
Labels: hacktoberfest-accepted

#99 Created find_lowest_common_ancestor_bst.cpp
  15. Binary Search Tree/find_lowest_common_ancestor_bst.cpp
Labels: hacktoberfest-accepted

#101 Best time to buy and sell stock(optimized)
  18. Greedy/Best time to buy and sell stock(optimized).py
Labels: hacktoberfest-accepted

#104 cses tree section -distinct colour solution
  cses tree solution-distinct colours
Labels: hacktoberfest-accepted

#105 Extended Euclid [C++] Implementation Added
  01. Mathematics/19_Extended_Euclid.cpp
Labels: hacktoberfest-accepted

#95 C++ code to Distance Query Problem
  22. Segment Tree/Forest_Queries.cpp
  Distance_Queries.cpp
Labels: hacktoberfest-accepted

#63 Searching in linked list.cpp
  10. Linked List/Searching in linked list.cpp
Labels: hacktoberfest-accepted

#61 Created and solved Valid Parentheses
  09. String/Valid Parentheses.cpp
  10. Linked List/Delete Node in a Linked List.cpp
Labels: hacktoberfest-accepted

#76 Top_k _frequent_elements.cpp
  16. Heap/top_k _frequent_eleemnt.cpp
Labels: hacktoberfest-accepted

#78 Added tower of hanoi
  03. Recursion/tower of hanoi.cpp
Labels: hacktoberfest-accepted

#56 Create Indices_of_the_numbers_with_given_sum
  04. Arrays/Indices_of_the_numbers_with_given_sum
Labels: hacktoberfest-accepted

#106 Create max-area-rectangle-binary-matrix.cpp
  11. Stack/max-area-rectangle-binary-matrix.cpp
Labels: hacktoberfest-accepted

#108 leetcode binary tree maximum path sum leetcode largest rectangle in h…
  .gitignore
  11. Stack/largest_rectangle_in_histogram.cpp
  15. Binary Search Tree/binary_tree_maximum_path_sum.cpp
Labels: hacktoberfest-accepted

#114 C++ program to generate a matrix in which matrix elements are bitwise OR of all row and column elements
  07. Matrix/Generate_Matrix.cpp
Labels: hacktoberfest-accepted

#116 Break Palindrome Problem
  09. String/Break_Palindrome.cpp
Labels: hacktoberfest-accepted

#115 Added Absolute Value
  01. Mathematics/6_AbsoluteValue.cpp
Labels: hacktoberfest-accepted

#119 Create reverse-a-linked-list.cpp
  10. Linked List/reverse-a-linked-list.cpp
Labels: hacktoberfest-accepted

#120 Added Leetcode problem solution to Count_Univalue_Subtress
  15. Binary Search Tree/Count_Univalue_Subtrees.cpp
Labels: hacktoberfest-accepted

#121 Max length of a concatenated string
  09. String/Maximum_Length_with_unique_characters.cpp
Labels: hacktoberfest-accepted

#122 RecoverBinary Tree added
  14. Tree/Recover-Binary-Tree.java
Labels: hacktoberfest-accepted

#124 Create agnostic_search.cpp
  15. Binary Search Tree/agnostic_search.cpp
Labels: duplicate, hacktoberfest-accepted

#125 Added binary search algorithm in C++
  05. Searching/binary_search.cpp
Labels: duplicate, hacktoberfest-accepted

#126 Created bfs_rotten_oranges.cpp
  17. Graph/bfs_rotten_oranges.cpp
Labels: hacktoberfest-accepted

#127 sparse matrix code using linked list
  10. Linked List/multiply_transpose_sparse_matrix.c
Labels: hacktoberfest-accepted

#130 Catalan Number Cpp
  20. Dynamic Programming/catalanDP.cpp
Labels: hacktoberfest-accepted

#131 Simple Queue and Stack added
  11. Stack/simple_stack.cpp
  12. Queue/simple_queue.c++
Labels: hacktoberfest-accepted

#132 Added search in 2D row wise sorted matrix in log(N) time
  05. Searching/Search2DMatrix.cpp
Labels: hacktoberfest-accepted

#134 Swap kth element in an array
  04. Arrays/swapKthElement.java
Labels: hacktoberfest-accepted

#136 Added solution in Array and String
  04. Arrays/15_Two Sum.cpp
  04. Arrays/16_4Sum.cpp
  09. String/4_Longest Palindromic Substring.cpp
  09. String/5_ZigZag Conversion.cpp
  09. String/6_Integer to Roman.cpp
Labels: hacktoberfest-accepted

#137 Added ternary search implementation
  05. Searching/ternary-search.cpp
Labels: hacktoberfest-accepted

#133 Added Count total subests with given sum
  02. Bit Magic/Q1.cpp
  20. Dynamic Programming/CountSubsetsWithGivenSum.cpp
Labels: hacktoberfest-accepted

#139 Standard Deviation (Solution)
  04. Arrays/StandardDeviation.cpp
Labels: hacktoberfest-accepted

#140 Added sort a linked list of 0,1,2's
  10. Linked List/sort_LinkedList_of_0_1_2's.cpp
Labels: hacktoberfest-accepted

#141 Create infix_to_postfix.cpp
  11. Stack/infix_to_postfix.cpp
Labels: hacktoberfest-accepted

#110 C++ solution of two knights problem
  Two_Knights.cpp
Labels: hacktoberfest-accepted

#143 Added code for breadth first search
  17. Graph/Breadth First Search.c
Labels: duplicate, hacktoberfest-accepted

#138 Simple BST added
  14. Tree/Inorder_BinaryTree.cpp
  15. Binary Search Tree/delete_in_BST.cpp
  15. Binary Search Tree/search_in_BST.cpp
  15. Binary Search Tree/simple_BST.cpp
  README.md
Labels: duplicate, hacktoberfest-accepted

#129 Winner of TicTacToe
  04. Arrays/Group_Anagrams.cpp
  07. Matrix/Winner_Tic_Tac_Toe.cpp
Labels: hacktoberfest-accepted

#190 Checking If linked list is a Palindrome
  10. Linked List/Checking if a linked list is Palindrome.txt
Labels: hacktoberfest-accepted

#189 Fractional Knapsack using cpp with STL
  18. Greedy/knapsack.cpp
Labels: duplicate, hacktoberfest-accepted

#187 Create Search in nearly sorted array
  05. Searching/Search in nearly sorted array.cpp
Labels: hacktoberfest-accepted

#186 Peak Element
  05. Searching/Peak Element.cpp
Labels: hacktoberfest-accepted

#192 added Equal Stacks c++
  11. Stack/EqualStacks.cpp
Labels: hacktoberfest-accepted

#191 Add Solution Problem about Graph, Greedy, and DP
  17. Graph/SpringLoaded.cpp
  18. Greedy/New-YearPresents.cpp
  20. Dynamic Programming/Eldorado.cpp
Labels: hacktoberfest-accepted

#194 Create AdjacencyMatrix.cpp
  AdjacencyMatrix.cpp
Labels: duplicate, hacktoberfest-accepted

#193 Create Generate Parentheses.cpp
  20. Dynamic Programming/Generate Parentheses.cpp
Labels: duplicate, hacktoberfest-accepted

#165 efficient approach with no division operation
  Product of Array Except Self.cpp
Labels: hacktoberfest-accepted

#164 three-pointers
  04. Arrays/17_three-pointer.c++
Labels: hacktoberfest-accepted

#163 Generating Subsets of a string.
  03. Recursion/Generate_Subsets.cpp
Labels: hacktoberfest-accepted

#167 bucket Sort
  06. Sorting/bucketSort.cpp
Labels: hacktoberfest-accepted

#168 Adding solution of Leetcode 739(Daily Temperatures)
  11. Stack/Daily_Temperatures.cpp
Labels: hacktoberfest-accepted

#169 Create subsets of an array.py
  19. Backtracking/subsets of an array.py
Labels: hacktoberfest-accepted

#158 Add MST algorithms
  17. Graph/kruskals.cpp
  17. Graph/prims.cpp
  17. Graph/primsOptimized.cpp
Labels: hacktoberfest-accepted

#157 Add files via upload
  16. Heap/Heap_sort.cpp
  16. Heap/Max_heap.cpp
Labels: hacktoberfest-accepted

#156 Add Word_break problem in trie
  21. Trie/Word_break.cpp
Labels: hacktoberfest-accepted

#154 Two sum -ii input array is sorted
  05. Searching/Two sum -ii input array is sorted
  08. Hashing/Longest substring without any repeating character
Labels: hacktoberfest-accepted

#159 added longest increasing subsequence code
  20. Dynamic Programming/Longest_increasing_subsequence.cpp
Labels: hacktoberfest-accepted

#152 Shortest Unique Prefix (Trie)
  21. Trie/shortest_unique_prefix.cpp
Labels: hacktoberfest-accepted

#171 added a new question of reversing a stack using another empty stack reversestack.cpp
  11. Stack/reversestack.cpp
Labels: hacktoberfest-accepted

#153 Create Square _root _of _a_number.cpp
  Square _root _of _a_number.cpp
Labels: hacktoberfest-accepted

#173 Added implementation of KMP Algorithm for pattern matching
  09. String/kmpStringMatching.c
Labels: hacktoberfest-accepted

#145 Added longest (strictly) increasing subsequence Dynamic programming p…
  20. Dynamic Programming/longest_increasing_subsequence.cpp
Labels: hacktoberfest-accepted

#148 Create INSERTION AT PARTICULAR POSITION.cpp
  10. Linked List/INSERTION AT PARTICULAR POSITION.cpp
Labels: hacktoberfest-accepted

#160 Create Fractional_Knapsack.cpp
  18. Greedy/Fractional_Knapsack.cpp
Labels: hacktoberfest-accepted

#174 Insert node in linked list
  10. Linked List/2.Insertion in Linked List.cpp
Labels: duplicate, hacktoberfest-accepted

#175 added stringsubsequence Dp solution
  20. Dynamic Programming/stringSubsequence.cpp
Labels: hacktoberfest-accepted

#183 Create basic_search.ccp
  05. Searching/basic_search.ccp
Labels: good first issue

#181 Binary Tree Preorder, Postorder, Inorder Traversal in Java with Iterative as well as Recursive
  14. Tree/Binary_Tree_Inorder_Traversal.java
  14. Tree/Binary_Tree_Postorder_Traversal.java
  14. Tree/Binary_Tree_Preorder_Traversal.java
  14. Tree/Inorder_Traversal_Recursive.java
  14. Tree/Postorder_Traversal_Recursive.java
  14. Tree/Preorder_Traversal_Recursive.java
Labels: hacktoberfest-accepted

#184 Find the position of element in an infinite sorted array.cpp
  05. Searching/Find the position of element in an infinite sorted array.cpp
Labels: hacktoberfest-accepted

#185 Nearest smaller to the left
  11. Stack/Nearest smaller to the left.cpp
Labels: hacktoberfest-accepted

#188 Added bucket_sort.cpp
  06. Sorting/bucket_sort.cpp
Labels: hacktoberfest-accepted

#195 Added Merge Intervals
  04. Arrays/Merge_intervals.cpp
Labels: hacktoberfest-accepted

#197 Basic Calculator
  11. Stack/Basic_Calculator.cpp
Labels: hacktoberfest-accepted

#198 Added pattern problems from pepcoding
  Patterns/pattern1.java
  Patterns/pattern10.java
  Patterns/pattern11.java
  Patterns/pattern12.java
  Patterns/pattern13.java
  Patterns/pattern14.java
  Patterns/pattern15.java
  Patterns/pattern16.java
  Patterns/pattern17.java
  Patterns/pattern18.java
  Patterns/pattern19.java
  Patterns/pattern2.java
  Patterns/pattern20.java
  Patterns/pattern3.java
  Patterns/pattern4.java
  Patterns/pattern5.java
  Patterns/pattern6.java
  Patterns/pattern7.java
  Patterns/pattern8.java
  Patterns/pattern9.java
Labels: hacktoberfest-accepted

#200 regular expression matching
  20. Dynamic Programming/Regular_Expression_Matching.cpp
  20. Dynamic Programming/WildCard_Matching.cpp
Labels: hacktoberfest-accepted

#202 Created find_diameter_binary_trees.cpp
  14. Tree/find_diameter_binary_trees.cpp
Labels: hacktoberfest-accepted

#203 Create Sort an array of 0s, 1s and 2s.cpp
  04. Arrays/Sort an array of 0s, 1s and 2s.cpp
Labels: hacktoberfest-accepted

#204 leetcode stack question
  11. Stack/removeDuplicates.cpp
Labels: hacktoberfest-accepted

#205 Added variation of BFS: word ladder problem
  17. Graph/wordLadder.cpp
Labels: hacktoberfest-accepted

#206 Array implementation of stack added
  11. Stack/ArrayImplementStack.cpp
Labels: hacktoberfest-accepted

#208 Added Cryptography Algo - AES Encryption Decryption
  24. Cryptography/AES_Enc_Dec.py
Labels: hacktoberfest-accepted

#211 Add files via upload
  03. Recursion/Nqueen.cpp
Labels: hacktoberfest-accepted

#214 added count_nodes.cpp
  14. Tree/count_node.cpp
Labels: hacktoberfest-accepted

#215 New code rabin_karp_algo_pattern_match.cpp
  09. String/rabin_karp_algo_pattern_match.cpp
Labels: hacktoberfest-accepted
